# Docsy config
#
# cSpell:ignore docsy fortawesome fontawesome webfonts

params:
  features:
    analytics:
      enabled: true
      goatCounter:
        code: code
  ui:
    readingTime:
      enable: true

  offlineSearch: true
  algolia_docsearch: false
  offlineSearchSummaryLength: 70
  offlineSearchMaxResults: 10
  prism_syntax_highlighting: false

  mermaid:
    enable: false
    theme: default
  plantuml:
    enable: false
    theme: default
    svg_image_url: https://www.plantuml.com/plantuml/svg/
    svg: false
  katex:
    enable: false
    html_dom_element: document.body
    mhchem:
      enable: true
  print:
    disable_toc: false
  markmap:
    enable: false

outputFormats:
  PRINT:
    baseName: index
    isHTML: true
    mediaType: text/html
    path: _print
    permalinkable: false

module:
  hugoVersion:
    extended: true
    min: 0.73.0
  mounts:
    - source: assets
      target: assets
    - source: node_modules/bootstrap
      target: assets/vendor/bootstrap
    - source: node_modules/@fortawesome/fontawesome-free
      target: assets/vendor/Font-Awesome
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts
    - source: static
      target: static
    - source: node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/webfonts
    # Mounts for projects using Docsy as an NPM package. The source path prefix
    # "../.." moves out of themes/docsy so that Docsy can find its dependencies.
    - source: ../../node_modules/bootstrap
      target: assets/vendor/bootstrap
    - source: ../../node_modules/@fortawesome/fontawesome-free
      target: assets/vendor/Font-Awesome
    - source: ../../node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/webfonts
