name = "PrivateDocsy"
license = "Apache 2.0"
licenselink = "https://github.com/LNA-DEV/PrivateDocsy/blob/main/LICENSE"
description = "A Hugo theme for technical documentation sites. Forked from Google but focused on privacy."
homepage = "https://docsy.dev"
tags = ["documentation", "multilingual", "customizable", "responsive", "docs", "privacy"]
features = []
min_version = 0.53

[author]
  name = "The PrivateDocsy Authors"
  homepage = "https://docsy.dev"
